bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('remove_from_bag/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
]

ssaw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.models import Product1
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                    null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """ Generate a random unique number using uuid"""
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """Update grand total each time a line item is added"""
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.delivery_cost = settings.DELIVERY_CHARGE
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)
        return

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(Product1, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and upgrade the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models

four_seasons = (
    ("Spring", "Spring"),
    ("Summer", "Summer"),
    ("Autumn", "Autumn"),
    ("Winter", "Winter"),
)


class Category1(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=10, choices=four_seasons)

    def __str__(self):
        return self.name

    def get_name(self):
        return self.name


class Product1(models.Model):
    category = models.ForeignKey('Category1', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    photographer = models.CharField(max_length=254, default=None, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product1, Category1


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product1
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category1.objects.all()
        friendly_names = [(c.id, c.get_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Product1, Category1
from .forms import ProductForm


def all_products(request):
    """A view showing all products, including filtered searches"""
    products = Product1.objects.all()

    category = None

    if request.GET:
        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category1.objects.filter(name__in=categories)

    context = {
        'products': products,
        'current_categories': category,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """A view showing individual products """
    product = get_object_or_404(Product1, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product1, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product1, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Add a Product</h5>
            <hr>
        </div>
    </div>
    
    <div class="row">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h5 class="text-muted">Edit a Product</h5>
            <hr>
        </div>
    </div>
    
    <div class="row">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-0" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <div class="card col-12 col-sm-10 col-md-8 col-lg-6">
                <div class="image-container mt-3">
                    {% if product.image %}
                    <a href="{{ product.image.url }}" target="_blank">
                        <img class="card-img-top img-fluid card-area" src="{{ product.image.url }}"
                            alt="{{ product.name }}">
                    </a>
                </div>
                <hr>
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }} <span
                            class="lead font-weight-bold mx-5">€{{ product.price }}</span></h5>
                    <p class="card-text">by {{ product.photographer }}</p>
                    {% if product.rating %}
                    <small class="text-muted"><i class="fas fa-star"></i>{{ product.rating }} /
                        5</small>
                    {% else %}
                    {% endif %}
                    {% if product.category %}
                    <a class="text-muted ml-4" href="{% url 'products' %}?category={{ product.category.name }}">
                        <i class="fas fa-tag mr-1"></i>{{ product.category.name }}
                    </a>
                    {% endif %}
                    {% if request.user.is_superuser %}
                    <small class="ml-3">
                        <a href="{% url 'edit_product' product.id %}">Edit</a>
                        <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                    </small>
                    {% endif %}
                </div>
                <form action="{% url 'add_to_bag' product.id %}" method="POST">
                    <div class="card-body">
                        {% if product.has_sizes %}
                        {% csrf_token %}
                        <strong>Sizes:</strong>
                        <select class="form-control w-25" name="product_size" id='id_product_size'>
                            <option value="A6">a6</option>
                            <option value="A5">a5</option>
                            <option value="A4" selected>a4</option>
                            <option value="A3">a3</option>
                        </select>
                    </div>
                    <div class="card-body">
                        <p><strong>Quantity:</strong></p>
                        <select class="form-control w-25" name="quantity" id="id_qty_{{ product.id }}">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                    </div>
                    <div class="card-body">
                        <input type="submit" class="col-12 btn btn-black rounded-0 text-uppercase"
                            value="Add to Bag">
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                    </div>
                </form>
            </div>
            {% else %}
            <h6 class="text-danger"><strong>sorry, not currently in stock.</strong></h6>
            {% endif %}
        </div>
    </div>
</div>
{% else %}
<h2 class="logo-font text-center">Product Placeholder</h2>
<hr>
<h5 class="logo-font text-center">Add Image from Admin</h5>
{% endif %}
{% endblock %}

products/templates/products/products.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3">
            <a class="category-badge text-decoration-none" href="{% url 'products' %}">
                <h2 class="logo-font text-black">Products</h2>
            </a>
            <a class="category-badge text-decoration-none" href="{% url 'products' %}?category=Spring">
                <span class="p-2 mt-2 badge badge-white text-black rounded-0 border border-dark">Spring</span>
            </a>
            <a class="category-badge text-decoration-none" href="{% url 'products' %}?category=Summer">
                <span class="p-2 mt-2 badge badge-white text-black rounded-0 border border-dark">Summer</span>
            </a>
            <a class="category-badge text-decoration-none" href="{% url 'products' %}?category=Autumn">
                <span class="p-2 mt-2 badge badge-white text-black rounded-0 border border-dark">Autumn</span>
            </a>
            <a class="category-badge text-decoration-none" href="{% url 'products' %}?category=Winter">
                <span class="p-2 mt-2 badge badge-white text-black rounded-0 border border-dark">Winter</span>
            </a>
            <hr class="w-50 mb-1">
        </div>
    </div>
    <div class="row">
        <div class="product-container col-10 offset-1">
            <div class="row mt-1 mb-2">
                <div class="col-12 col-md-6">
                    <p class="text-muted mt-3 text-center text-md-left">
                        Search Found: <span class="text-black">{{ products|length }} Items</span>
                    </p>
                </div>
            </div>
            <div class="row">
                {% for product in products %}
                <div class="col-sm-12 col-lg-6">
                    <div class="card h-100 border-0">
                        {% if product.image %}
                        <a href="{% url 'product_detail' product.id %}">
                            <img class="card-img-top img-fluid card-area" src="{{ product.image.url }}"
                                alt="{{ product.name }}">
                        </a>
                        <div class="card-body pb-0">
                            <p class="mb-0">{{ product.name }}</p>
                        </div>
                        <div class="card-footer bg-white pt-0 border-0 text-left">
                            <div class="row">
                                <div class="col">
                                    <p class="lead mb-0 text-left font-weight-bold">${{ product.price }}</p>
                                    {% if product.category %}
                                    <p class="small mt-1 mb-0">
                                        <a class="text-muted"
                                            href="{% url 'products' %}?category={{ product.category.name }}">
                                            <i class="fas fa-tag mr-1"></i>{{ product.category.name }}
                                        </a>
                                    </p>
                                    {% endif %}
                                    {% if product.rating %}
                                    <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} /
                                        5</small>
                                    {% else %}
                                    <small class="text-muted">No Rating</small>
                                    {% endif %}
                                    {% if request.user.is_superuser %}
                                        <small class="ml-3">
                                            <a href="{% url 'edit_product' product.id %}">Edit</a>
                                            <a class="text-danger" href="{% url 'delete_product' product.id %}">Delete</a>
                                        </small>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% else %}
                        {% endif %}
                    </div>
                </div>

                {% if forloop.counter|divisibleby:1 %}
                <div class="col-12 d-block d-lg-none mb-5">
                    <hr>
                </div>
                {% endif %}

                {% if forloop.counter|divisibleby:2 %}
                <div class="col-12 d-none d-lg-block mb-5">
                    <hr>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="btt-button shadow-sm rounded-0 border border-black">
    <a class="btt-link d-flex h-100">
        <i class="fas fa-arrow-up text-black mx-auto my-auto"></i>
    </a>	
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
		$('.btt-link').click(function(e) {
			window.scrollTo(0,0)
		})
	</script>
{% endblock %}